# Generated by Django 4.2.6 on 2023-10-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_note_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
        migrations.AddField(
            model_name='question',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='question',
            name='questions',
            field=models.TextField(null=True),
        ),
    ]
