# Generated by Django 4.2.6 on 2023-10-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_question_body_question_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.TextField(null=True),
        ),
    ]
