# Generated by Django 4.2.6 on 2023-10-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
