/**
 * This code was generated by Builder.io.
 */
import React from "react";
// import { Link } from "react-scroll";
import "./sidebar.css";
import Avatar from "./Ellipse 212.png";
// import History from "../fluenthistory32filled@2x.png";
// import Fileu from "../dashboard-black-24dp-1-1@2x.png";

const Sidebar = () => {
  return (
    <section id="yul">
      <div className="frame">
        <div className="group">
          <img className="ellipse" alt="Ellipse" src= {Avatar}/>
          <div className="text-wrapper">Akshat</div>
          <div className="div">Product Designer</div>
        </div>
        <div className="overlap">
          <div className="group-2">
            <div className="group-3">
              <a href="#">
                <div className="text-wrapper-2">Upload </div>
                <img className="img" alt="Dashboard black" src="" />
              </a>
            </div>
            <div className="div-wrapper">
              <a href="#">
                <div className="text-wrapper-3">History</div>
                <img
                  className="fluent-history"
                  alt="Fluent history"
                  // src={History}
                />
              </a>
            </div>

            <div className="rectangle" />
          </div>
        </div>
        <div className="rectangle-2" />
        <div className="text-wrapper-6">Chatfiles.ai</div>
      </div>
    </section>
  );
};

export default Sidebar;